### ISSUE TITLE
Need to include MQSNOAUT: "yes"

### ISSUE THREAD

**Issue by powersplay** [WASdev/sample.docker.mq#3]
In order to get the Liberty sender & receiver talking to each other via MQ, it was necessary to include `MQSNOAUT: "yes"` as an environment variable for the mq container.

FYI.  After successfully executing on Docker for Mac, I moved it to a UCP environment on AWS.  Since links are no longer supported, this was the Dockerfile that I used to make it deploy as a service with  `docker stack deploy -c docker-compose.yml MQSample` (after pushing the build images up to Docker Hub.)

```
version: '3'
services:

  mqfull:
    image: {hub-repository}/test-mq:1.0
    environment:
      LICENSE: accept
      MQ_QMGR_NAME: QM1
      MQSNOAUT: "yes"
    ports:
      - "1414:1414"
      - "9443:9443"
  sender:
    image: {hub-repository}/test-sender:1.0
    ports:
     - "10080:9080"
     - "10443:9443"
  receiver:
    image: {hub-repository}/test-receiver:1.0
    ports:
     - "10081:9080"
     - "10444:9443"
```
